name: CI

on:
  push:
    branches: ["**"]
    tags:
      - v*
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        elixir: [1.12.2]
        otp: [24.0.2]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ matrix.otp }}
          elixir-version: ${{ matrix.elixir }}
      - run: mix deps.get
      - run: mix test
      - uses: lee-dohm/generate-elixir-docs@v1
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./doc
